groups:
- name: laundrybasket
  jobs:
  - test-isiticecreamyet-prs

resource_types:
- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

- name: laundry-pool
  type: docker-image
  source:
    repository: businesscritical/laundry-pool

- name: pool
  type: docker-image
  source:
    repository: concourse/pool-resource

resources:
- name: isiticecreamyet-pr
  type: pull-request
  source:
    repo: businesscritical/isiticecreamyet
    access_token: {{access_token}}

- name: bosh-envs
  type: laundry-pool
  source:
    uri: git@github.com:cloudfoundry/capi-ci-private.git
    branch: locks
    pool: bosh-directors
    private_key: {{private_key}}

- name: laundrybasket
  type: git
  source:
    branch: master
    uri: https://github.com/utako/laundrybasket.git

- name: capi-ci-private
  type: git
  source:
    branch: laundry
    private_key: {{private_key}}
    uri: git@github.com:cloudfoundry/capi-ci-private.git

- name: resource-version
  type: semver
  source:
    driver: git
    uri: git@github.com:utako/laundrybasket.git
    branch: version
    file: version
    private_key: {{private_key}}

jobs:
- name: clean-dirty-bosh-directors
  plan:

- name: test-isiticecreamyet-prs
  plan:
  - aggregate:
    - get: isiticecreamyet-pr
      trigger: true
    - get: laundrybasket
    - get: resource-version
  - put: isiticecreamyet-pr
    params:
      path: isiticecreamyet-pr
      status: pending
  - put: bosh-envs
    params: {acquire: true}
  - put: resource-version
    params:
      bump: patch
  - task: test_isiticecreamyet
    file: laundrybasket/ci/test_isiticecreamyet.yml
    ensure:
      put: bosh-envs
      params: {release: bosh-envs}
    on_success:
      put: isiticecreamyet-pr
      params:
        path: isiticecreamyet-pr
        status: success
    on_failure:
      put: isiticecreamyet-pr
      params:
        path: isiticecreamyet-pr
        status: failure
  - put: bosh-envs
    params: {release: bosh-envs}

- name: create-directors
  plan:
    - get: laundrybasket
    - task: make-director
      file: laundrybasket/ci/make-director.yml
      params:
        AWS_ACCESS_KEY_ID: {{runtime_aws_key_id}}
        AWS_SECRET_ACCESS_KEY: {{runtime_aws_access_key}}
    - put: bosh-directors
      params:
        add: 'job_output'
