#!/bin/bash
set -e -x

echo "=== Testing IS IT ICE CREAM YET PR ==="

cd isiticecreamyet-pr

version=$(cat ../resource-version/version)
length=$((${#version}-1))
lastDigit=${version:$i:1}
isOdd=$(( lastDigit & 1 ))


echo "lastDigit: $lastDigit"
echo "EXIT STATUS: $isOdd"

exit $isOdd
