#!/bin/bash
set -e -x

echo "=== Testing IS IT ICE CREAM YET PR ==="

version=$(cat resource-version/version)
length=$((${#version}-1))
lastDigit=${version:$length:1}
isOdd=$(( lastDigit & 1 ))


echo "lastDigit: $lastDigit"
echo "EXIT STATUS: $isOdd"

exit $isOdd
